apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-nginx-alpine
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vishwakarmavijay4031/argocd-project.git
    path: ./nginx-alpine
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-alpine-ns
  syncPolicy:
    syncOptions:
    - CreateNamespace: true
    automated:
      prune: true
      selfHeal: true
